=== Nooree0413/RecipeHouse/xml/cuisines.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Cuisines">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Cuisine" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Type"/>
              <xs:element type="xs:string" name="Dish"/>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Nooree0413/RecipeHouse/xml/cuisines.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cuisines.xsl"?>
<Cuisines xsi:noNamespaceSchemaLocation= "cuisines.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Cuisine id="1">
    <Type>Indian</Type>
    <Dish>Spicy Potatoes</Dish>
  </Cuisine>
  <Cuisine id="2">
    <Type>Chinese</Type>
    <Dish>Noodles</Dish>
  </Cuisine>
  <Cuisine id="3">
    <Type>Chinese</Type>
    <Dish>Chicken Schezwan</Dish>
  </Cuisine>
  <Cuisine id="4">
    <Type>Japanese</Type>
    <Dish>Sushi</Dish>
  </Cuisine>
  <Cuisine id="5">
    <Type>Italian</Type>
    <Dish>Pizza</Dish>
  </Cuisine>
  <Cuisine id="6">
    <Type>Turkish</Type>
    <Dish>Turkish Rice</Dish>
  </Cuisine>
</Cuisines>
